#!/bin/sh
# Copyright © Mixed Mode GmbH 2017
#
# schroot is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# schroot is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#####################################################################

set -e

. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"
. "$SETUP_DATA_DIR/common-config"


shell="${CHROOT_PATH}/bin/sh"
resolv="/etc/resolv.conf"
dst="${CHROOT_PATH}${resolv}"


if [ "$STAGE" = "setup-start" ] || \
   [ "$STAGE" = "setup-recover" ] ; then
    [ -h "$dst" ] && mv $dst ${dst}.backup
    cp $resolv $dst

elif [ "$STAGE" = "setup-stop" ] ; then
    [ -h "$dst.backup" ] && mv ${dst}.backup $dst
    exit 0
fi






